### PR TITLE
Handle missing content length

### PR DESCRIPTION
**Pull request by donatello**
- If missing, the object length is unknown, and we set it as -1 in ObjectInfo.
    
Alternative to fix problem described in #151

### CODE REVIEW

**Comment by donatello** [comment]
This is on top of #152 - so only the latest comment is relevant to this PR. The previous commits will be merged separately.

**Comment by qnikst** [comment]
@donatello, I’m heavily -1 for this approach. It makes things worse in the failure case, hiding the error from the user . Would you agree with PR where I’ll set Accept-Encoding in the head query that approach should allow to keep old API, and use Head GetObject to get object size and tolerate working with clever servers. I if so I can prepare such

**Comment by harshavardhana** [comment]
> @donatello, I’m heavily -1 for this approach. It makes things worse in the failure case, hiding the error from the user . Would you agree with PR where I’ll set Accept-Encoding in the head query that approach should allow to keep old API, and use Head GetObject to get object size and tolerate working with clever servers. I if so I can prepare such

If adding a header allows server to always send expected headers then that is a better approach than setting content-length as -1.

**Comment by qnikst** [comment]
Setting Accept-Encoding to identity does fix the issue. I’ll prepare a PR.

**Comment by donatello** [comment]
Closing as we are going with an alternative approach.

**Pull request closed without merging**
