### PR TITLE
WIP: API.md

### PR DESCRIPTION
**Pull request by donatello**

### CODE REVIEW

**Comment by krisis** [comment]
This template looks good to me.

**Comment by harshavardhana** [comment]
Builds are failing for this package is there a problem in putObject() ?

**Comment by donatello** [comment]
> Builds are failing for this package is there a problem in putObject() ?

@harshavardhana This is happening as the play server is too slow/far away for the tests and also because each test in the live-server testsuite is started simultaneously by the test harness (too much parallelism). We will address this in upcoming patches. The solution is have fewer tests, and to do more checks in a single test - this avoid excessive parallelism (though it works fine if the minio server is local).

**Comment by donatello** [comment]
Merging this for now, so remaining sections can be split up and completed.

**Pull request merged**
